### ISSUE TITLE
Getting an exception when using AutoFill

### ISSUE THREAD

**Issue by ionuttbara** [SimpleMobileTools/Simple-Keyboard#248]
Hi. With last version of this app , when i try to autofill infomation with Enpass Password from Simple Keyboard i get Error 5 which it gone from main function.
Steps to reproduce:
1. Autofill password and the password manager will not open.

**Comment by tibbi** [comment]
was it working well previously?

**Comment by ionuttbara** [comment]
no.
i installed recently the f-droid release of app, i get exception everytime when i press autofill

**Comment by ionuttbara** [comment]
i am coming with some updates (and videos)
when i press auto fill from simple keyboard in Via Browser it said an Exception was obtained. Also in Microsoft Edge and Chrome it making the browser to crash.
I don't know if that is coming from Password Manager, because with Samsung Keyboard AutoFill is working.

https://github.com/SimpleMobileTools/Simple-Keyboard/assets/76656855/eb647922-edb0-436a-b487-a09f990a44a9


https://github.com/SimpleMobileTools/Simple-Keyboard/assets/76656855/e6ef120c-bb38-4499-84ac-dcd0b02d19b1


https://github.com/SimpleMobileTools/Simple-Keyboard/assets/76656855/c5f83d4a-dfc9-439b-9085-cb2f16b96deb

**Comment by ionuttbara** [comment]
i am come with an update. 
reinstalled the 5.4.7 version and the autofill works, but in 5.4.8 is same result.

**Comment by FintasticMan** [comment]
Here is a crash log, might help: ```
type: crash
osVersion: google/lynx/lynx:13/TQ3A.230901.001/2023100300:user/release-keys
package: com.simplemobiletools.keyboard:23
process: com.simplemobiletools.keyboard
processUptime: 7713 + 311 ms
installer: org.fdroid.basic

java.lang.RuntimeException: Not allowed to write file descriptors here
	at android.os.Parcel.nativeAppendFrom(Native Method)
	at android.os.Parcel.appendFrom(Parcel.java:760)
	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1787)
	at android.os.Bundle.writeToParcel(Bundle.java:1389)
	at android.os.Parcel.writeBundle(Parcel.java:1336)
	at android.content.Intent.writeToParcel(Intent.java:11608)
	at android.os.Parcel.writeTypedObject(Parcel.java:2159)
	at android.app.IActivityTaskManager$Stub$Proxy.startActivityIntentSender(IActivityTaskManager.java:2171)
	at android.app.Activity.startIntentSenderForResultInner(Activity.java:5935)
	at android.app.Activity.startIntentSenderForResult(Activity.java:5873)
	at android.view.autofill.AutofillClientController.autofillClientAuthenticate(AutofillClientController.java:484)
	at android.view.autofill.AutofillManager.authenticate(AutofillManager.java:2453)
	at android.view.autofill.AutofillManager.-$$Nest$mauthenticate(Unknown Source:0)
	at android.view.autofill.AutofillManager$AutofillManagerClient.lambda$authenticate$3(AutofillManager.java:3903)
	at android.view.autofill.AutofillManager$AutofillManagerClient$$ExternalSyntheticLambda3.run(Unknown Source:12)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7940)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ExecInit.main(ExecInit.java:49)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:355)

```
